# Generated by Django 2.2.4 on 2020-06-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_carrier', models.CharField(blank=True, max_length=2)),
                ('flight_numbers', models.CharField(blank=True, max_length=200)),
                ('departure_airports', models.CharField(blank=True, default='SGV', max_length=3)),
                ('arrival_airports', models.CharField(blank=True, default='SGV', max_length=3)),
                ('departure_times', models.CharField(blank=True, default='12:00', max_length=5)),
                ('arrival_times', models.CharField(blank=True, default='12:00', max_length=5)),
                ('departure_dates', models.CharField(blank=True, default='31-MAR-2021', max_length=100)),
                ('arrival_dates', models.CharField(blank=True, default='31-MAR-2021', max_length=100)),
                ('carriers', models.CharField(blank=True, default='YY', max_length=2)),
                ('rbds', models.CharField(blank=True, default='na', max_length=50)),
                ('cabins', models.CharField(blank=True, default='na', max_length=50)),
                ('bags', models.CharField(blank=True, default='na', max_length=50)),
                ('itinerary_origin', models.CharField(blank=True, max_length=3)),
                ('itinerary_destination', models.CharField(blank=True, max_length=3)),
                ('itinerary_departure_time', models.CharField(blank=True, max_length=5)),
                ('itinerary_arrival_time', models.CharField(blank=True, max_length=5)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_price', models.FloatField(default=0.0)),
                ('travel_time', models.PositiveIntegerField(default=0)),
                ('passenger_count', models.PositiveIntegerField(default=0)),
                ('seat_count', models.PositiveIntegerField(default=0)),
                ('flight_count', models.CharField(default='2,2', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origins', models.CharField(blank=True, max_length=50)),
                ('destinations', models.CharField(blank=True, max_length=50)),
                ('dates', models.CharField(blank=True, max_length=50)),
                ('adt', models.IntegerField(blank=True, default=1)),
                ('cnn', models.IntegerField(blank=True, default=0)),
                ('inf', models.IntegerField(blank=True, default=0)),
                ('options_in_cache', models.IntegerField(blank=True, default=0)),
                ('observations', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, default=0, null=True)),
                ('cheapest_price', models.FloatField(default=999999)),
                ('quickest_time', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dragonfly.Itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('profile_id', models.CharField(default='0', max_length=2)),
                ('reservation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dragonfly.Reservation')),
            ],
        ),
        migrations.AddField(
            model_name='itinerary',
            name='search_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonfly.Search'),
        ),
    ]
