# Generated by Django 3.0.3 on 2020-06-19 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='reservation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dragonfly.Reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='itinerary_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dragonfly.Itinerary'),
        ),
    ]
