# Generated by Django 3.0.3 on 2020-06-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0002_auto_20200619_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='ptc',
            field=models.CharField(default='ADT', max_length=3),
        ),
    ]
