# Generated by Django 3.0.3 on 2020-06-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.CharField(default='sgvolpe@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
